# Generated by Django 4.2.7 on 2026-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('service_type', models.CharField(max_length=200, verbose_name='Tipo de Serviço')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('pdf_url', models.URLField(blank=True, null=True, verbose_name='URL do PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Cliente')),
                ('problem_description', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em Andamento'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
    ]
